FROM registry.access.redhat.com/jboss-datavirt-6/datavirt63-openshift

LABEL Name="JDV-EXT" \
      Version="latest"

# Copy add-on details
COPY install.sh /extensions/
COPY data /extensions/data/
#COPY modules /extensions/modules/

